package com.ruoyi.ai.mapper;
import java.util.List; import org.apache.ibatis.annotations.*; import com.ruoyi.ai.domain.AiPendingToolCall;
public interface AiPendingToolCallMapper {
 String FIELDS="select pending_id as pendingId,call_id as callId,conversation_id as conversationId,user_id as userId,tool_name as toolName,arguments_json as argumentsJson,risk_level as riskLevel,model_id as modelId,model_code as modelCode,reasoning_effort as reasoningEffort,run_id as runId,capability_protocol as capabilityProtocol,page_id as pageId,route,page_instance_id as pageInstanceId,page_version as pageVersion,status,create_time as createTime,expire_time as expireTime,resolved_time as resolvedTime ";
 @Insert("insert into ai_pending_tool_call(call_id,conversation_id,user_id,tool_name,arguments_json,risk_level,model_id,model_code,reasoning_effort,run_id,capability_protocol,page_id,route,page_instance_id,page_version,status,create_time,expire_time) values(#{callId},#{conversationId},#{userId},#{toolName},#{argumentsJson},#{riskLevel},#{modelId},#{modelCode},#{reasoningEffort},#{runId},#{capabilityProtocol},#{pageId},#{route},#{pageInstanceId},#{pageVersion},'PENDING',sysdate(),date_add(sysdate(), interval 10 minute))") @Options(useGeneratedKeys=true,keyProperty="pendingId") int insert(AiPendingToolCall p);
 @Select(FIELDS+"from ai_pending_tool_call where conversation_id=#{conversationId} and call_id=#{callId} and status='PENDING' and expire_time>sysdate() limit 1") AiPendingToolCall selectByCall(@Param("conversationId")Long conversationId,@Param("callId")String callId);
 @Select(FIELDS+"from ai_pending_tool_call where conversation_id=#{conversationId} and status='PENDING' and expire_time>sysdate() order by pending_id") List<AiPendingToolCall> selectPendingByConversation(Long conversationId);
 @Select(FIELDS+"from ai_pending_tool_call where conversation_id=#{conversationId} order by pending_id") List<AiPendingToolCall> selectByConversation(Long conversationId);
 @Update("update ai_pending_tool_call set status='RESOLVED',resolved_time=sysdate() where pending_id=#{pendingId} and status='PENDING' and expire_time>sysdate()") int resolve(Long pendingId);
 @Update("update ai_pending_tool_call set status=#{status},resolved_time=sysdate() where run_id=#{runId} and status='PENDING'") int cancelByRun(@Param("runId")Long runId,@Param("status")String status);
}