package com.ruoyi.ai.mapper;
import java.util.List; import org.apache.ibatis.annotations.*; import com.ruoyi.ai.domain.AiRun;
public interface AiRunMapper {
 String FIELDS="select run_id as runId,client_run_key as clientRunKey,conversation_id as conversationId,user_id as userId,model_id as modelId,model_code as modelCode,reasoning_effort as reasoningEffort,status,cancel_reason as cancelReason,superseded_by_run_id as supersededByRunId,system_prompt_version as systemPromptVersion,compaction_prompt_version as compactionPromptVersion,input_tokens as inputTokens,cache_read_tokens as cacheReadTokens,cache_write_tokens as cacheWriteTokens,total_tokens as totalTokens,create_time as createTime,update_time as updateTime,end_time as endTime ";
 @Insert("insert into ai_run(client_run_key,conversation_id,user_id,model_id,model_code,reasoning_effort,status,system_prompt_version,compaction_prompt_version,create_time,update_time) values(#{clientRunKey},#{conversationId},#{userId},#{modelId},#{modelCode},#{reasoningEffort},#{status},#{systemPromptVersion},#{compactionPromptVersion},sysdate(),sysdate())") @Options(useGeneratedKeys=true,keyProperty="runId") int insert(AiRun r);
 @Select(FIELDS+"from ai_run where run_id=#{runId}") AiRun selectById(Long runId);
 @Select(FIELDS+"from ai_run where client_run_key=#{clientRunKey} and user_id=#{userId} limit 1") AiRun selectByClientKey(@Param("clientRunKey")String clientRunKey,@Param("userId")Long userId);
 @Select(FIELDS+"from ai_run where conversation_id=#{conversationId} and status in ('RUNNING','WAITING_TOOL','CANCEL_REQUESTED') order by run_id desc limit 1") AiRun selectActiveByConversation(Long conversationId);
 @Select(FIELDS+"from ai_run where user_id=#{userId} and status in ('RUNNING','WAITING_TOOL','CANCEL_REQUESTED') order by run_id") List<AiRun> selectActiveByUser(Long userId);
 @Update("update ai_run set status=#{status},cancel_reason=#{reason},update_time=sysdate(),end_time=case when #{status} in ('CANCELLED','SUPERSEDED','COMPLETED','FAILED') then sysdate() else end_time end where run_id=#{runId} and user_id=#{userId} and status in ('RUNNING','WAITING_TOOL','CANCEL_REQUESTED')") int updateOwnedState(@Param("runId")Long runId,@Param("userId")Long userId,@Param("status")String status,@Param("reason")String reason);
 @Update("update ai_run set status='SUPERSEDED',superseded_by_run_id=#{newRunId},cancel_reason='STEERING',update_time=sysdate(),end_time=sysdate() where run_id=#{oldRunId} and status in ('RUNNING','WAITING_TOOL','CANCEL_REQUESTED')") int supersede(@Param("oldRunId")Long oldRunId,@Param("newRunId")Long newRunId);
 @Update("update ai_run set status=#{status},update_time=sysdate() where run_id=#{runId} and status in ('RUNNING','WAITING_TOOL')") int updateActiveState(@Param("runId")Long runId,@Param("status")String status);
 @Update("update ai_run set status='COMPLETED',update_time=sysdate(),end_time=sysdate() where run_id=#{runId} and status='RUNNING'") int complete(Long runId);
 @Update("update ai_run set status='FAILED',cancel_reason=#{reason},update_time=sysdate(),end_time=sysdate() where run_id=#{runId} and status in ('RUNNING','WAITING_TOOL','CANCEL_REQUESTED')") int fail(@Param("runId")Long runId,@Param("reason")String reason);
 @Update("update ai_run set input_tokens=input_tokens+#{input},cache_read_tokens=cache_read_tokens+#{cacheRead},cache_write_tokens=cache_write_tokens+#{cacheWrite},total_tokens=total_tokens+#{total},update_time=sysdate() where run_id=#{runId}") int updateUsage(@Param("runId")Long runId,@Param("input")long input,@Param("cacheRead")long cacheRead,@Param("cacheWrite")long cacheWrite,@Param("total")long total);
}